repos:
- repo: local
  hooks:
    - id: format
      name: Run Python code formatter
      entry: task format
      language: system
      stages: [pre-commit]
      types: [python]
      always_run: true
- repo: local
  hooks:
    - id: lint
      name: Run Python linting
      entry: task lint
      language: system
      stages: [pre-commit]
      types: [python]
      always_run: true
